### ISSUE TITLE
Chat Tpl

### ISSUE THREAD

**Issue by tsandrini** [tsandrini/node-chat#3]
- víceménně přenechám na tobě, zde akorát zanechám své nápady
- 1. dala by se někde přes nějaké kolečko upravit barvička uživatele
  1. asi bych zanechal chat přes celé okno. To nám zanechá možnost tam mít více lidí.
     3 . měla by tam být možnost "vystoupit" z chatu, což prakticky znamená nějaký button, nebo by se to        dalo přimíchat k "rádoby kolečku" upravování barvičky
  2.  ....

**Comment by zatkoma** [comment]
Prosím o feedback

**Comment by tsandrini** [comment]
Ok, to je cool a prozatím to bude stačit bohatě.
Díky ;)
